// <auto-generated />
using System;
using EvaluacionDesempenoApi.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EvaluacionDesempenoApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241015225633_IdentityTables")]
    partial class IdentityTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AltEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AltName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CdLanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("IdEmployee")
                        .HasColumnType("int");

                    b.Property<bool>("IndChangePassword")
                        .HasColumnType("bit");

                    b.Property<bool>("IndEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CdLanguage");

                    b.HasIndex("IdEmployee");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.Areas", b =>
                {
                    b.Property<string>("CdArea")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("IdArea")
                        .HasColumnType("int");

                    b.Property<string>("NameArea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CdArea");

                    b.ToTable("Areas", "Masters");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.Colors", b =>
                {
                    b.Property<int>("IdColor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdColor"), 1L, 1);

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColorNameEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColorNameES")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdColor");

                    b.ToTable("Colors", "Masters");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.Divisions", b =>
                {
                    b.Property<string>("CdDivisions")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("IdDivisions")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CdDivisions");

                    b.ToTable("Divisions", "Masters");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.Employees", b =>
                {
                    b.Property<int>("IdEmployees")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmployees"), 1L, 1);

                    b.Property<string>("CdDivisions")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<int?>("IDResponsible")
                        .HasColumnType("int");

                    b.Property<int>("IdPosition")
                        .HasColumnType("int");

                    b.Property<string>("Identification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastNames")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Names")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEmployees");

                    b.HasIndex("CdDivisions");

                    b.HasIndex("IDResponsible");

                    b.HasIndex("IdPosition");

                    b.ToTable("Employees", "Masters");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.Escales", b =>
                {
                    b.Property<int>("IdEscales")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEscales"), 1L, 1);

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEscales");

                    b.ToTable("Escales", "Masters");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.EscalesValues", b =>
                {
                    b.Property<int>("IdEscalesValues")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEscalesValues"), 1L, 1);

                    b.Property<int>("IdEscales")
                        .HasColumnType("int");

                    b.Property<bool>("IndMayor")
                        .HasColumnType("bit");

                    b.Property<int>("IndOrder")
                        .HasColumnType("int");

                    b.Property<string>("NameValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEscalesValues");

                    b.HasIndex("IdEscales");

                    b.ToTable("EscalesValues", "Masters");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.EvaluationRecord", b =>
                {
                    b.Property<int>("IdEvaluationRecord")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEvaluationRecord"), 1L, 1);

                    b.Property<string>("CdEvaluationStates")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ColorFlag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionFlag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("EndDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EvaluationFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("FinalCalification")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("IdEmployee")
                        .HasColumnType("int");

                    b.Property<int>("IdEvaluations")
                        .HasColumnType("int");

                    b.Property<int>("IdEvaluator")
                        .HasColumnType("int");

                    b.Property<int?>("IdFlag")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("StartDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("IdEvaluationRecord");

                    b.HasIndex("CdEvaluationStates");

                    b.HasIndex("IdEmployee");

                    b.HasIndex("IdEvaluations");

                    b.HasIndex("IdEvaluator");

                    b.ToTable("EvaluationRecord", "Evaluation");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.Evaluations", b =>
                {
                    b.Property<int>("IdEvaluations")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEvaluations"), 1L, 1);

                    b.Property<string>("CdDivisions")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CdTypeEvaluation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("EndDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("IDProcessLeader")
                        .HasColumnType("int");

                    b.Property<int?>("IdEscales")
                        .HasColumnType("int");

                    b.Property<int?>("IdFlag")
                        .HasColumnType("int");

                    b.Property<int>("IdQuestionary")
                        .HasColumnType("int");

                    b.Property<bool?>("IndApplyEB")
                        .HasColumnType("bit");

                    b.Property<bool?>("IndEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("StartDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("IdEvaluations");

                    b.HasIndex("CdDivisions");

                    b.HasIndex("IDProcessLeader");

                    b.HasIndex("IdEscales");

                    b.HasIndex("IdFlag");

                    b.HasIndex("IdQuestionary");

                    b.ToTable("Evaluations", "Evaluation");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.EvaluationsPositions", b =>
                {
                    b.Property<int>("IdEvaluationsPositions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEvaluationsPositions"), 1L, 1);

                    b.Property<int>("IdEvaluations")
                        .HasColumnType("int");

                    b.Property<int>("IdPosition")
                        .HasColumnType("int");

                    b.HasKey("IdEvaluationsPositions");

                    b.HasIndex("IdEvaluations");

                    b.HasIndex("IdPosition");

                    b.ToTable("EvaluationsPositions", "Evaluation");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.EvaluationStates", b =>
                {
                    b.Property<string>("CdEvaluationStates")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("IdEvaluationStates")
                        .HasColumnType("int");

                    b.Property<string>("NameEvaluationStatesEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEvaluationStatesES")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CdEvaluationStates");

                    b.ToTable("EvaluationStates", "Masters");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.Files", b =>
                {
                    b.Property<int>("IdFile")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFile"), 1L, 1);

                    b.Property<string>("CdFileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CdMonths")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdEvaluationRecord")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("IdFile");

                    b.HasIndex("CdFileType");

                    b.ToTable("Files", "Evaluation");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.FileTypes", b =>
                {
                    b.Property<string>("CdFileType")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdFileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameFileTypeEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameFileTypeES")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CdFileType");

                    b.ToTable("FileTypes", "Masters");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.FlagRules", b =>
                {
                    b.Property<int>("IdFlagRules")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFlagRules"), 1L, 1);

                    b.Property<string>("CdFlagType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionES")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdColor")
                        .HasColumnType("int");

                    b.Property<int>("IdFlag")
                        .HasColumnType("int");

                    b.Property<decimal?>("MaxValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MinValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdFlagRules");

                    b.HasIndex("CdFlagType");

                    b.HasIndex("IdColor");

                    b.HasIndex("IdFlag");

                    b.ToTable("FlagRules", "Evaluation");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.Flags", b =>
                {
                    b.Property<int>("IdFlag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFlag"), 1L, 1);

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameFlagEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameFlagES")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdFlag");

                    b.ToTable("Flags", "Evaluation");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.FlagTypes", b =>
                {
                    b.Property<string>("CdFlagType")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FlagTypeNameEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlagTypeNameES")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdFlagType")
                        .HasColumnType("int");

                    b.HasKey("CdFlagType");

                    b.ToTable("FlagTypes", "Masters");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.Formats", b =>
                {
                    b.Property<int>("IdFormats")
                        .HasColumnType("int");

                    b.Property<string>("CdFormats")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionFormats")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameFormats")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("display")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdFormats");

                    b.ToTable("Formats", "Masters");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.Frequencies", b =>
                {
                    b.Property<string>("Cdfrequency")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Idfrequency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cdfrequency");

                    b.ToTable("Frequencies", "Masters");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.Groups", b =>
                {
                    b.Property<int>("IdGroups")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGroups"), 1L, 1);

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameES")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdGroups");

                    b.ToTable("Groups", "Masters");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.KpiRecordDetails", b =>
                {
                    b.Property<int>("IdKpiRecordDetails")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKpiRecordDetails"), 1L, 1);

                    b.Property<string>("CdFormats")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CdMonths")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cdfrequency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Control")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayFormats")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Earned")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FileType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdEvaluationRecord")
                        .HasColumnType("int");

                    b.Property<decimal?>("Incentive")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("KpiFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RealValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Weight")
                        .HasColumnType("int");

                    b.Property<bool>("Won")
                        .HasColumnType("bit");

                    b.HasKey("IdKpiRecordDetails");

                    b.HasIndex("IdEvaluationRecord");

                    b.ToTable("KpiRecordDetails", "Evaluation");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.Languages", b =>
                {
                    b.Property<string>("CdLanguage")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("IdLanguage")
                        .HasColumnType("int");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CdLanguage");

                    b.ToTable("Languages", "Masters");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.Positions", b =>
                {
                    b.Property<int>("IdPosition")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPosition"), 1L, 1);

                    b.Property<string>("NamePosition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPosition");

                    b.ToTable("Positions", "Masters");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.Profiles", b =>
                {
                    b.Property<string>("CdProfile")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdProfile")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileNameEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileNameES")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CdProfile");

                    b.ToTable("Profiles", "Security");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.Questionaries", b =>
                {
                    b.Property<int>("IdQuestionary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdQuestionary"), 1L, 1);

                    b.Property<string>("CdArea")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CdQuestionaryType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdQuestionary");

                    b.HasIndex("CdArea");

                    b.HasIndex("CdQuestionaryType");

                    b.ToTable("Questionaries", "Evaluation");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.QuestionariesConfig", b =>
                {
                    b.Property<int>("IdQuestionaryConfig")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdQuestionaryConfig"), 1L, 1);

                    b.Property<string>("Cdfrequency")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Control")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayFormats")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdQuestionary")
                        .HasColumnType("int");

                    b.Property<int>("IdQuestions")
                        .HasColumnType("int");

                    b.Property<int?>("Incentive")
                        .HasColumnType("int");

                    b.Property<bool>("NoApplyScale")
                        .HasColumnType("bit");

                    b.Property<int?>("Weight")
                        .HasColumnType("int");

                    b.HasKey("IdQuestionaryConfig");

                    b.HasIndex("Cdfrequency");

                    b.HasIndex("IdQuestionary");

                    b.HasIndex("IdQuestions");

                    b.ToTable("QuestionariesConfig", "Evaluation");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.QuestionaryTypes", b =>
                {
                    b.Property<string>("CdQuestionaryType")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("IdQuestionaryType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CdQuestionaryType");

                    b.ToTable("QuestionaryTypes", "Masters");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.QuestionGroupRelation", b =>
                {
                    b.Property<int>("IdQuestionGroupRelation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdQuestionGroupRelation"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdGroups")
                        .HasColumnType("int");

                    b.Property<int>("IdQuestions")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdQuestionGroupRelation");

                    b.HasIndex("IdGroups");

                    b.HasIndex("IdQuestions");

                    b.ToTable("QuestionGroupRelation", "Evaluation");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.Questions", b =>
                {
                    b.Property<int>("IdQuestions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdQuestions"), 1L, 1);

                    b.Property<string>("CdArea")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<int>("IdFormats")
                        .HasColumnType("int");

                    b.Property<int>("IdQuestionType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameES")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdQuestions");

                    b.HasIndex("CdArea");

                    b.HasIndex("IdQuestionType");

                    b.ToTable("Questions", "Evaluation");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.QuestionType", b =>
                {
                    b.Property<int>("IdQuestionType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdQuestionType"), 1L, 1);

                    b.Property<string>("CdQuestionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameQuestionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdQuestionType");

                    b.ToTable("QuestionType", "Masters");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.RecordDetails", b =>
                {
                    b.Property<int>("IdRecordDetails")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRecordDetails"), 1L, 1);

                    b.Property<decimal?>("Average")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Calification")
                        .HasColumnType("int");

                    b.Property<string>("CdQuestionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlagColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlagDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupNameEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupNameES")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdEvaluationRecord")
                        .HasColumnType("int");

                    b.Property<int>("IdFlag")
                        .HasColumnType("int");

                    b.Property<int>("IdGroups")
                        .HasColumnType("int");

                    b.Property<int>("IdQuestions")
                        .HasColumnType("int");

                    b.Property<bool>("NoApplyScale")
                        .HasColumnType("bit");

                    b.Property<string>("ResponseDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalCalification")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Weight")
                        .HasColumnType("int");

                    b.HasKey("IdRecordDetails");

                    b.HasIndex("IdEvaluationRecord");

                    b.ToTable("RecordDetails", "Evaluation");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.RecordDetailsTemp", b =>
                {
                    b.Property<int>("IdRecordDetails")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRecordDetails"), 1L, 1);

                    b.Property<decimal?>("Average")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Calification")
                        .HasColumnType("int");

                    b.Property<string>("CdQuestionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlagColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlagDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupNameEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupNameES")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdEvaluationRecord")
                        .HasColumnType("int");

                    b.Property<int>("IdFlag")
                        .HasColumnType("int");

                    b.Property<int>("IdGroups")
                        .HasColumnType("int");

                    b.Property<int>("IdQuestions")
                        .HasColumnType("int");

                    b.Property<bool>("NoApplyScale")
                        .HasColumnType("bit");

                    b.Property<string>("ResponseDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalCalification")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Weight")
                        .HasColumnType("int");

                    b.HasKey("IdRecordDetails");

                    b.HasIndex("IdEvaluationRecord");

                    b.ToTable("RecordDetailsTemp", "Evaluation");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.Users", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"), 1L, 1);

                    b.Property<string>("AltEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AltName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CdLanguage")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdEmployee")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<bool?>("IndChangePassword")
                        .HasColumnType("bit");

                    b.Property<bool?>("IndEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUser");

                    b.HasIndex("CdLanguage");

                    b.HasIndex("IdEmployee")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.ApplicationUser", b =>
                {
                    b.HasOne("EvaluacionDesempenoApi.Models.Entities.Languages", null)
                        .WithMany()
                        .HasForeignKey("CdLanguage")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EvaluacionDesempenoApi.Models.Entities.Employees", null)
                        .WithMany()
                        .HasForeignKey("IdEmployee");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.Employees", b =>
                {
                    b.HasOne("EvaluacionDesempenoApi.Models.Entities.Divisions", "Divisions")
                        .WithMany("Employees")
                        .HasForeignKey("CdDivisions");

                    b.HasOne("EvaluacionDesempenoApi.Models.Entities.Employees", "Responsible")
                        .WithMany("Subordinates")
                        .HasForeignKey("IDResponsible");

                    b.HasOne("EvaluacionDesempenoApi.Models.Entities.Positions", "Positions")
                        .WithMany("Employees")
                        .HasForeignKey("IdPosition")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Divisions");

                    b.Navigation("Positions");

                    b.Navigation("Responsible");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.EscalesValues", b =>
                {
                    b.HasOne("EvaluacionDesempenoApi.Models.Entities.Escales", "Escales")
                        .WithMany("EscalesValues")
                        .HasForeignKey("IdEscales")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Escales");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.EvaluationRecord", b =>
                {
                    b.HasOne("EvaluacionDesempenoApi.Models.Entities.EvaluationStates", "EvaluationStates")
                        .WithMany("EvaluationRecords")
                        .HasForeignKey("CdEvaluationStates");

                    b.HasOne("EvaluacionDesempenoApi.Models.Entities.Employees", "Employee")
                        .WithMany("EvaluationsAsEmployee")
                        .HasForeignKey("IdEmployee");

                    b.HasOne("EvaluacionDesempenoApi.Models.Entities.Evaluations", "Evaluation")
                        .WithMany("EvaluationRecords")
                        .HasForeignKey("IdEvaluations")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EvaluacionDesempenoApi.Models.Entities.Employees", "Evaluator")
                        .WithMany("EvaluationsAsEvaluator")
                        .HasForeignKey("IdEvaluator")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Evaluation");

                    b.Navigation("EvaluationStates");

                    b.Navigation("Evaluator");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.Evaluations", b =>
                {
                    b.HasOne("EvaluacionDesempenoApi.Models.Entities.Divisions", "Divisions")
                        .WithMany("Evaluations")
                        .HasForeignKey("CdDivisions");

                    b.HasOne("EvaluacionDesempenoApi.Models.Entities.Employees", "Employees")
                        .WithMany("Questionaries")
                        .HasForeignKey("IDProcessLeader");

                    b.HasOne("EvaluacionDesempenoApi.Models.Entities.Escales", "Escales")
                        .WithMany("Evaluations")
                        .HasForeignKey("IdEscales");

                    b.HasOne("EvaluacionDesempenoApi.Models.Entities.Flags", "Flags")
                        .WithMany("Evaluations")
                        .HasForeignKey("IdFlag");

                    b.HasOne("EvaluacionDesempenoApi.Models.Entities.Questionaries", "Questionaries")
                        .WithMany("Evaluations")
                        .HasForeignKey("IdQuestionary")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Divisions");

                    b.Navigation("Employees");

                    b.Navigation("Escales");

                    b.Navigation("Flags");

                    b.Navigation("Questionaries");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.EvaluationsPositions", b =>
                {
                    b.HasOne("EvaluacionDesempenoApi.Models.Entities.Evaluations", "Evaluations")
                        .WithMany("EvaluationsPositions")
                        .HasForeignKey("IdEvaluations")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EvaluacionDesempenoApi.Models.Entities.Positions", "Positions")
                        .WithMany("EvaluationsPositions")
                        .HasForeignKey("IdPosition")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluations");

                    b.Navigation("Positions");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.Files", b =>
                {
                    b.HasOne("EvaluacionDesempenoApi.Models.Entities.FileTypes", "FileType")
                        .WithMany("Files")
                        .HasForeignKey("CdFileType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileType");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.FlagRules", b =>
                {
                    b.HasOne("EvaluacionDesempenoApi.Models.Entities.FlagTypes", "FlagTypes")
                        .WithMany("FlagRules")
                        .HasForeignKey("CdFlagType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EvaluacionDesempenoApi.Models.Entities.Colors", "Colors")
                        .WithMany("FlagRules")
                        .HasForeignKey("IdColor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EvaluacionDesempenoApi.Models.Entities.Flags", "Flags")
                        .WithMany("FlagRules")
                        .HasForeignKey("IdFlag")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colors");

                    b.Navigation("FlagTypes");

                    b.Navigation("Flags");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.Formats", b =>
                {
                    b.HasOne("EvaluacionDesempenoApi.Models.Entities.Questions", "Questions")
                        .WithOne("Formats")
                        .HasForeignKey("EvaluacionDesempenoApi.Models.Entities.Formats", "IdFormats")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.KpiRecordDetails", b =>
                {
                    b.HasOne("EvaluacionDesempenoApi.Models.Entities.EvaluationRecord", "EvaluationRecord")
                        .WithMany("KpiRecordDetails")
                        .HasForeignKey("IdEvaluationRecord")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EvaluationRecord");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.Questionaries", b =>
                {
                    b.HasOne("EvaluacionDesempenoApi.Models.Entities.Areas", "Area")
                        .WithMany("Questionaries")
                        .HasForeignKey("CdArea");

                    b.HasOne("EvaluacionDesempenoApi.Models.Entities.QuestionaryTypes", "QuestionaryTypes")
                        .WithMany("Questionaries")
                        .HasForeignKey("CdQuestionaryType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("QuestionaryTypes");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.QuestionariesConfig", b =>
                {
                    b.HasOne("EvaluacionDesempenoApi.Models.Entities.Frequencies", "Frequencies")
                        .WithMany("QuestionariesConfig")
                        .HasForeignKey("Cdfrequency");

                    b.HasOne("EvaluacionDesempenoApi.Models.Entities.Questionaries", "Questionary")
                        .WithMany("QuestionariesConfig")
                        .HasForeignKey("IdQuestionary")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EvaluacionDesempenoApi.Models.Entities.Questions", "Questions")
                        .WithMany("QuestionariesConfig")
                        .HasForeignKey("IdQuestions")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Frequencies");

                    b.Navigation("Questionary");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.QuestionGroupRelation", b =>
                {
                    b.HasOne("EvaluacionDesempenoApi.Models.Entities.Groups", "Groups")
                        .WithMany("QuestionGroupRelations")
                        .HasForeignKey("IdGroups")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EvaluacionDesempenoApi.Models.Entities.Questions", "Questions")
                        .WithMany("QuestionGroupRelations")
                        .HasForeignKey("IdQuestions")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Groups");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.Questions", b =>
                {
                    b.HasOne("EvaluacionDesempenoApi.Models.Entities.Areas", "Areas")
                        .WithMany("Questions")
                        .HasForeignKey("CdArea");

                    b.HasOne("EvaluacionDesempenoApi.Models.Entities.QuestionType", "QuestionType")
                        .WithMany("Questions")
                        .HasForeignKey("IdQuestionType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Areas");

                    b.Navigation("QuestionType");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.RecordDetails", b =>
                {
                    b.HasOne("EvaluacionDesempenoApi.Models.Entities.EvaluationRecord", "EvaluationRecord")
                        .WithMany("RecordDetails")
                        .HasForeignKey("IdEvaluationRecord")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EvaluationRecord");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.RecordDetailsTemp", b =>
                {
                    b.HasOne("EvaluacionDesempenoApi.Models.Entities.EvaluationRecord", "EvaluationRecord")
                        .WithMany("RecordDetailsTemp")
                        .HasForeignKey("IdEvaluationRecord")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EvaluationRecord");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.Users", b =>
                {
                    b.HasOne("EvaluacionDesempenoApi.Models.Entities.Languages", "Languages")
                        .WithMany("Users")
                        .HasForeignKey("CdLanguage");

                    b.HasOne("EvaluacionDesempenoApi.Models.Entities.Employees", "Employees")
                        .WithOne("Users")
                        .HasForeignKey("EvaluacionDesempenoApi.Models.Entities.Users", "IdEmployee")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employees");

                    b.Navigation("Languages");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("EvaluacionDesempenoApi.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("EvaluacionDesempenoApi.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EvaluacionDesempenoApi.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("EvaluacionDesempenoApi.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.Areas", b =>
                {
                    b.Navigation("Questionaries");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.Colors", b =>
                {
                    b.Navigation("FlagRules");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.Divisions", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Evaluations");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.Employees", b =>
                {
                    b.Navigation("EvaluationsAsEmployee");

                    b.Navigation("EvaluationsAsEvaluator");

                    b.Navigation("Questionaries");

                    b.Navigation("Subordinates");

                    b.Navigation("Users")
                        .IsRequired();
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.Escales", b =>
                {
                    b.Navigation("EscalesValues");

                    b.Navigation("Evaluations");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.EvaluationRecord", b =>
                {
                    b.Navigation("KpiRecordDetails");

                    b.Navigation("RecordDetails");

                    b.Navigation("RecordDetailsTemp");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.Evaluations", b =>
                {
                    b.Navigation("EvaluationRecords");

                    b.Navigation("EvaluationsPositions");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.EvaluationStates", b =>
                {
                    b.Navigation("EvaluationRecords");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.FileTypes", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.Flags", b =>
                {
                    b.Navigation("Evaluations");

                    b.Navigation("FlagRules");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.FlagTypes", b =>
                {
                    b.Navigation("FlagRules");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.Frequencies", b =>
                {
                    b.Navigation("QuestionariesConfig");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.Groups", b =>
                {
                    b.Navigation("QuestionGroupRelations");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.Languages", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.Positions", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("EvaluationsPositions");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.Questionaries", b =>
                {
                    b.Navigation("Evaluations");

                    b.Navigation("QuestionariesConfig");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.QuestionaryTypes", b =>
                {
                    b.Navigation("Questionaries");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.Questions", b =>
                {
                    b.Navigation("Formats")
                        .IsRequired();

                    b.Navigation("QuestionGroupRelations");

                    b.Navigation("QuestionariesConfig");
                });

            modelBuilder.Entity("EvaluacionDesempenoApi.Models.Entities.QuestionType", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
